CREATE TABLESPACE "PRUEBAS" LOGGING 
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\PRUEBAS.dbf' SIZE 24M 
EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;


DROP USER usuario CASCADE;

CREATE USER usuario IDENTIFIED BY password
       DEFAULT TABLESPACE PRUEBAS  
       TEMPORARY TABLESPACE temp
       ACCOUNT UNLOCK;

GRANT "CONNECT" TO usuario;
GRANT "RESOURCE" TO usuario;

GRANT ALTER ANY INDEX TO usuario;
GRANT ALTER ANY SEQUENCE TO usuario;
GRANT ALTER ANY TABLE TO usuario;
GRANT ALTER ANY TRIGGER TO usuario;
GRANT CREATE ANY INDEX TO usuario;
GRANT CREATE ANY SEQUENCE TO usuario;
GRANT CREATE ANY SYNONYM TO usuario;
GRANT CREATE ANY TABLE TO usuario;
GRANT CREATE ANY TRIGGER TO usuario;
GRANT CREATE ANY VIEW TO usuario;
GRANT CREATE PROCEDURE TO usuario;
GRANT CREATE PUBLIC SYNONYM TO usuario;
GRANT CREATE TRIGGER TO usuario;
GRANT CREATE VIEW TO usuario;
GRANT DELETE ANY TABLE TO usuario;
GRANT DROP ANY INDEX TO usuario;
GRANT DROP ANY SEQUENCE TO usuario;
GRANT DROP ANY TABLE TO usuario;
